Backup/LocalSearchSystem/LocalSearchSystem/urls.py
from django.contrib import admin
from django.urls import path, include
import User.views as userview
import WikiNews.views as wikinewsview


urlpatterns = [
    path('', userview.LoginView),
    path('admin/', admin.site.urls),
    path('user/', include('User.urls')),
    path('wikinews/', include('WikiNews.urls'))

]

Backup/LocalSearchSystem/User/urls.py
from django.urls import path
from .import views


app_name = 'User'

urlpatterns = [
    path('login', views.LoginView),
    path('loginaction', views.LoginAction, name='loginaction'),
    path('login', views.LogoutView, name = "logout"),
    path('usermanagement', views.UserManagementView, name = "usermanagement"),
    path('newuser', views.NewUserView, name = "newuser"),
    path('Searchpage', views.SearchView, name = "searchpage"),
]

Backup/LocalSearchSystem/WikiNews/urls.py
from django.urls import path
from .import views

app_name = 'WikiNews'

urlpatterns = [
    path('item-management/', views.ItemManagementView, name='itemmanagement'),
    path('web-scrapping/', views.WebScrappingView, name = "webscrapping"),
    path('itemdetails/<int:itemId>', views.ItemDetailView, name = "itemdetails"),
    path('search-result/', views.SearchResultView, name = "searchresult"),
    path('search-item-result/', views.SearchItemResultView, name='searchitemresult'),
    path('scrapping/', views.ScrapWikiNews, name='scrapping'),
    path('item/del/<int:itemId>',views.DelItem)

]

Backup/LocalSearchSystem/User/models.py
from django.db import models
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)

# Create your models here.

class WikiNewsUser(models.Model):
    id = models.AutoField(primary_key=True)
    username = models.CharField(max_length=200, null=True, unique=True)
    password = models.CharField(max_length=100)
    is_admin = models.BooleanField(default=True)

    class Meta:
        db_table = 'WikiNewsUser'

Backup/LocalSearchSystem/User/forms.py
from django.contrib.auth import authenticate
from django.contrib.auth.password_validation import validate_password
from django.core import exceptions
from django.core.validators import validate_email
from django.forms import ModelForm
from django import  forms
from .models import  WikiNewsUser
from django.contrib.auth.forms import ReadOnlyPasswordHashField




class NewUserForm(forms.Form):
    username = forms.CharField(label='username' ,max_length=255)
    password = forms.CharField(widget=forms.PasswordInput(), max_length=100)
    password2 = forms.CharField(widget=forms.PasswordInput(), max_length=100)
    isadmin = forms.BooleanField(label='isadmin')



class UserLoginForm(forms.Form):
    username = forms.CharField(max_length=30)
    password = forms.CharField(widget=forms.PasswordInput())

    def clean(self):
        users = WikiNewsUser.objects.filter(username=self.cleaned_data['username'])
        user = authenticate(username = self.cleaned_data['username'], password=self.cleaned_data['password'])
        if len(users) == 0 and user is None:
            raise forms.ValidationError("Invalid username or password. Please try again!")
        return self.cleaned_data

    def login(self, request):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        return user

Backup/LocalSearchSystem/User/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from .models import WikiNewsUser
from .import views
from .forms import NewUserForm
from django.contrib.auth import authenticate, login, logout
from django.template.context_processors import csrf
from django.utils.datastructures import MultiValueDictKeyError
from django.core.paginator import  Paginator, InvalidPage, EmptyPage, PageNotAnInteger



def LoginView(request):
    return render(request, 'index.html')



def LoginAction(request):
    if request.method == 'POST':
        username = request.POST.get("username")
        user = WikiNewsUser.objects.raw('select id, is_admin from wikinewsuser where username= %s',[username])
        for field in user:
            print(field.is_admin)
        if field.is_admin == True:
            return UserManagementView(request)
        else:
            return SearchView(request)
    return render(request, 'index.html')


def UserManagementView(request):
    userList = WikiNewsUser.objects.all()
    return render(request, 'user-management.html', {'data': userList})


def NewUserView(request):
    form = NewUserForm(request.POST)
    if request.method == 'POST':
        try:
            print(form.data)
            model = WikiNewsUser()
            model.username = form.data['username']
            model.password = form.data['password']
            try:
                is_admin = request.POST['isadmin']
            except MultiValueDictKeyError:
                is_admin = False
            if 'isadmin' in form.data:
                model.is_admin = True
            else:
                model.is_admin = False
            model.save()
            # return render(request, 'user-management.html')
        except:
           return HttpResponseRedirect('/user/usermanagement')
    return  HttpResponseRedirect('/user/usermanagement')


def SearchView(request):
    return render(request, 'search.html')

def LogoutView(request):
    return render(request, 'index.html')

Backup/LocalSearchSystem/User/templates/add-user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>AddUser</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="/static/css/index.css">

</head>

<body>

    <header>
        <a class="title" href="#"><img src="/static/images/logo.png" alt="logo" style="width:60px;"> Local Search System</a>
    </header>

    <form class="form" action="{% url 'User:loginaction' %}" method="POST">
        {% csrf_token %}
        <img class="login_icon" src="/static/images/loginnew.png" alt="logo">
        <p>Email: </p>
        <input class="input" type="text" id="email" name="email">
        <p>Password: </p>
        <input class="input" type="password" id="password" name="password">
        <p>Confirm Password: </p>
        <input class="input" type="password" id="confirmpassword" name="confirmpassword">
        <input type="checkbox" id="admin" name="admin">
        <label for="admin">Admin</label><br>
        <input class="button" type="submit" value="Add User"/>

    </form>

    <script src="/static/js/index.js"></script>
</body>
</html>

Backup/LocalSearchSystem/User/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Home</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="/static/css/index.css">
    
</head>

<body>  
    
    <header>
        <a class="title" href="#"><img src="/static/images/logo.png" alt="logo" style="width:60px;"> Local Search System</a>
    </header>
    
    <form class="form" action="{% url 'User:loginaction' %}" method="POST">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}" />
        <fieldset>
        <div class="col-lg-10 col-lg-offset-2">
            {% if error_message %}
                <p><strong>{{ error_message }}</strong></p>
            {% endif %}
        </div>
        <div class="col-sm-offset-2 col-sm-10">
                <span class="text-danger small">
                    {% if form.errors %}
                        {{  form.non_field_errors }}
                    {% endif %}
                </span>
        </div>
             <img class="login_icon" src="/static/images/loginnew.png" alt="logo">
            <div class="form-group">
            <label for="username" class="control-label">Username: </label>
            <div class="input">
                <input type="text" class="input" id="username" name="username" placeholder="User Name"
                       required>
            </div>
        </div>
        <div class="form-group">
            <label for="password" class="control-label">Password: </label>
            <div class="input">
                <input type="password" class="input" id="password" name="password" placeholder="Password"
                       required>
            </div>
        </div>

        <div>
            <input type="submit" class="button" value="Login"/><br>
        </div>
    </fieldset>

<!--        <p>User Name: </p>-->
<!--        <input class="input" type="text" id="username" name="username">-->
<!--        <p>Password: </p>-->
<!--        <input class="input" type="password" id="password" name="password">-->
<!--        <input class="button" type="submit" value="Login">-->
<!--        <span><a href=""><p style="text-align:center">Create User</p><a href=""><p style="text-align:center">Forgot Password?</p></a></a></span>-->

    </form>


    
    <script src="/static/js/index.js"></script>
</body>
</html>

Backup/LocalSearchSystem/User/templates/user-management.html
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>User Management</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="http://cdn.datatables.net/1.10.2/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="Stylesheet" href=" " "text="" javascript""="" src=""https://code.jquery.com/jquery-1.12.3.js">
    <script type="text/javascript" src="https://code.jquery.com/jquery-1.12.3.js"></script>  
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script type="text/javascript" src="http://code.jquery.com/jquery-1.7.1.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
    <link rel="stylesheet" href="/static/css/common.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
	
<body>
	
    <header>
        <a class="title" href="#"><img src="/static/images/logo.png" alt="logo" style="width:60px;"> Local Search System</a>
    </header>
    
    <div class="sidebar">
      <a href="{% url 'User:usermanagement' %}" class="active"><i class="fa fa-users navtext" title="User management"></i> User Management</a>
      <a href="{% url 'WikiNews:itemmanagement' %}"><i class="fa fa-list navtext" title="Item management"></i> Item Management</a>
      <a href="{% url 'WikiNews:webscrapping' %}"><i class="fa fa-globe navtext" title="Web scrapping" ></i> Web Scraping</a>
      <a href="{% url 'User:logout' %}"><i class="fa fa-sign-out navtext" title="Sign out"></i> Sign Out</a>
    </div>

    <div class="container-lg tabledata">
        <div class="table-responsive">
            <div class="table-wrapper">
                <div class="table-title">
                    <div class="row">
                        <div class="col-sm-8"><h2>User <b>Details</b></h2></div>
                        <div class="col-sm-4">
                            <button type="button" class="btn btn-info add-new" data-toggle="modal" data-target="#newuserModal"id="addnew"><i class="fa fa-plus"></i> Add New</button>
                        </div>
                        <div class="modal" id="newuserModal" role="dialog">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                                            <h4 class="modal-title">Create User</h4>
                                    </div>
                                    <div class="modal-body">
                                        <form id="newuserform" action="{% url 'User:newuser' %}" method="POST">
                                            {% csrf_token %}
                                            <p>Username:</p>
                                            <input class="input" type="text" id="username" name="username">
                                            <p>Password:</p>
                                            <input class="input" type="password" id="password" name="password">
                                            <p>Confirm Password:</p>
                                            <input class="input" type="password" id="confirmpassword" name="confirmpassword">
                                            <p>Is Admin User:<input type="checkbox" id="isadmin" name="isadmin"></p>
                                            <input class="button" type="submit" value="Add User"/>
                                        </form>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <table id="user_table" class="table table-bordered">
                    <thead>
                        <tr>
                            <th>User Id</th>
                            <th>UserName</th>
                            <th>Password</th>
                            <th>Is Admin</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for x in data %}
                        <tr>
                            <td>{{x.id}}</td>
                            <td>{{x.username}}</td>
                            <td>{{x.password}}</td>
                            <td>{{x.is_admin}}</td>
                            <td>
                                <a class="add" title="Add" data-toggle="tooltip"><i class="material-icons">&#xE03B;</i></a>
                                <a class="edit" title="Edit" data-toggle="tooltip"><i class="material-icons">&#xE254;</i></a>
                                <a class="delete" title="Delete" data-toggle="tooltip"><i class="material-icons">&#xE872;</i></a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>

    </div>
    <script src="/static/js/user-management.js"></script>
</body>
</html>