Backup/LocalSearchSystem/LocalSearchSystem/urls.py
from django.contrib import admin
from django.urls import path, include
import User.views as userview
import WikiNews.views as wikinewsview


urlpatterns = [
    path('', userview.LoginView),
    path('admin/', admin.site.urls),
    path('user/', include('User.urls')),
    path('wikinews/', include('WikiNews.urls'))

]

Backup/LocalSearchSystem/User/urls.py
from django.urls import path
from .import views


app_name = 'User'

urlpatterns = [
    path('login', views.LoginView),
    path('loginaction', views.LoginAction, name='loginaction'),
    path('login', views.LogoutView, name = "logout"),
    path('usermanagement', views.UserManagementView, name = "usermanagement"),
    path('newuser', views.NewUserView, name = "newuser"),
    path('Searchpage', views.SearchView, name = "searchpage"),
]

Backup/LocalSearchSystem/WikiNews/urls.py
from django.urls import path
from .import views

app_name = 'WikiNews'

urlpatterns = [
    path('item-management/', views.ItemManagementView, name='itemmanagement'),
    path('web-scrapping/', views.WebScrappingView, name = "webscrapping"),
    path('itemdetails/<int:itemId>', views.ItemDetailView, name = "itemdetails"),
    path('search-result/', views.SearchResultView, name = "searchresult"),
    path('search-item-result/', views.SearchItemResultView, name='searchitemresult'),
    path('scrapping/', views.ScrapWikiNews, name='scrapping'),
    path('item/del/<int:itemId>',views.DelItem)

]

Backup/LocalSearchSystem/WikiNews/models.py
from django.db import models


# Create your models here.
# Creating Item table

class Item(models.Model):
    itemname = models.CharField(primary_key=True, max_length=200)
    itemsummary = models.CharField(max_length=45)
    lastupdated = models.DateField(max_length=45)

    class Meta:
        db_table = 'Item'


# Creating custom field type that can store a data contains text and images in MySQL
class BlobField(models.Field):
    description = "Blob"
    def db_type(self, connection):
        return 'blob'


# Creating Item Details table
class ItemDetails(models.Model):
    serialnumber = models.AutoField(primary_key = True)
    Item = models.ForeignKey('Item', on_delete=models.CASCADE, db_column='itemname')
    article = BlobField(blank=True)
    collaberation = BlobField(blank=True)
    opinions = BlobField(blank=True)
    sources = models.TextField(blank=True)
    relatedarticles = models.TextField(blank=True)
    externallinks = models.TextField(blank=True)

    class Meta:
        db_table = 'ItemDetails'


class Items(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=200, null=True)
    content = models.CharField(max_length=1000, null=True)

    class Meta:
        db_table = 'Items'



class WikiNewsItem(models.Model):
    id = models.AutoField(primary_key = True)
    title = models.CharField(max_length=500, null=True)
    text = models.TextField()
    image = models.TextField()
    lastUpdated = models.DateField(null=True)

    class Meta:
        db_table = 'WikiNewsItem'

Backup/LocalSearchSystem/WikiNews/views.py
from django.shortcuts import render
import scrapy
import re
import pandas as pd
import unicodedata
from scrapy.crawler import CrawlerProcess
from urllib.parse import urlparse
from twisted.internet import reactor, defer
from scrapy.crawler import CrawlerRunner
from scrapy.utils.log import configure_logging
from .models import WikiNewsItem

# Create your views here.

result = []
all_urls = []
Paragraph_Data = []
continents = []
continents_urls = []


class Wikipedia(scrapy.Spider):
    name = "Wikipedia"
    # start_urls = [
    #     "https://en.wikinews.org/wiki/Main_Page"
    # ]

    def parse(self, response):
        for sel in response.xpath('//center//big//b'):
            title = sel.xpath('a/text()').extract()
            link = sel.xpath('a/@href').extract()
            continents.append(zip(title, link))


class Wikinews(scrapy.Spider):
    name = "Wikinews"

    def parse(self, response):
        for sel in response.xpath('//ul/li'):
            title = sel.xpath('a/text()').extract()
            link = sel.xpath('a/@href').extract()
            result.append((title[0], link[0]))


class Wikinews_items(scrapy.Spider):
    name = "Wikinews_items"
    allowed_domains = ['en.wikinews.org']

    def parse(self, response):
        parsed_uri = urlparse(response.url)
        domain = '{uri.scheme}://{uri.netloc}/'.format(uri=parsed_uri)

        def _clean(value):
            value = ' '.join(value)
            value = value.replace('\n', '')
            value = unicodedata.normalize("NFKD", value)
            value = re.sub(r' , ', ', ', value)
            value = re.sub(r' \( ', ' (', value)
            value = re.sub(r' \) ', ') ', value)
            value = re.sub(r' \)', ') ', value)
            value = re.sub(r'\[\d.*\]', ' ', value)
            value = re.sub(r' +', ' ', value)
            return value.strip()

        strings = ""
        for i in range(0, 100):
            try:
                for node in response.xpath('//*[@id="mw-content-text"]/div/p[{}]'.format(i)):
                    text = _clean(node.xpath('string()').extract())
                    if len(text):
                        strings = strings + text + "<br>"
            except Exception as error:
                pass

        try:
            image = 'https:' + response.xpath('//img[@class="thumbimage"]/@src').extract_first()
        except:
            image = ""

        paragraph_data = {
            'title': response.css('#firstHeading::text').extract_first(),
            'lastUpdated': response.xpath('//*[@id="publishDate"]/@title').extract_first(),
            'image': image,
            'text': strings
        }
        Paragraph_Data.append(paragraph_data)


configure_logging()
runner = CrawlerRunner()


@defer.inlineCallbacks
def crawl(url):
    yield runner.crawl(Wikipedia,start_urls=[url])
    for title, link in continents[0]:
        con_cat = 'https://en.wikinews.org/wiki/Category:' + link.replace('/wiki/', '')
        continents_urls.append(con_cat)

    yield runner.crawl(Wikinews, start_urls=continents_urls)
    df = pd.DataFrame(data=result, columns=["title", "link"])
    df.link = 'https://en.wikinews.org' + df.link
    all_urls = list(df.link)

    yield runner.crawl(Wikinews_items, start_urls=all_urls)
    reactor.stop()


def ScrapWikiNews(request):
    if request.method == 'POST':
        url = request.POST.get('urlinput')
        crawl(url)
        reactor.run()
        wikinewsdata = pd.DataFrame(Paragraph_Data)

        # wikinewsdata['image'] = wikinewsdata['image'].apply(lambda x: ('https:' + x) if x != None else x)
        # print(wikinewsdata)
        items = WikiNewsItem.objects.all()
        titles=[]
        for item in items:
            titles.append(item.title)
        wikinewsdata=wikinewsdata[wikinewsdata["title"].isin(titles) == False]
        print(wikinewsdata)
        try:
            WikiNewsItem.objects.bulk_create(WikiNewsItem(**vals) for vals in wikinewsdata.to_dict('records'))
        except:
            pass

    return  render(request,'web-scrapping.html')



def ItemManagementView(request):
    itemList = WikiNewsItem.objects.all()
    return render(request, 'item-management.html', {'itemList': itemList})

def WebScrappingView(request):
    return render(request, 'web-scrapping.html')

def ItemDetailView(request, itemId):
    print(itemId)
    items = WikiNewsItem.objects.filter(id=itemId)
    paragraphs =[]
    for field in items:
        content = field.text
        print(content)
        paragraphs = content.split('<br>')

    return render(request, 'details.html', {'items':items,'paragraphs':paragraphs})


def SearchView(request):
    return render(request, 'search.html')

def SearchResultView(request):
    return render(request,'search-result.html')

def SearchItemResultView(request):
    return render(request, 'search-item-result.html')



def DelItem(request,itemId):
    # if request.session.get('username')==None:
    #     return HttpResponseRedirect('/users/login')
    print(itemId)
    item=WikiNewsItem.objects.get(id=itemId)
    item.delete()
    return ItemManagementView(request)

Backup/LocalSearchSystem/WikiNews/templates/details.html
<!DOCTYPE html>
<html>

<head>
	<meta charset="utf-8">
	<meta http-equiv="content-type" content="text/html; charset=windows-1252">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Details</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" href="/static/css/home.css">
	<link rel="stylesheet" href="/static/css/common.css">
    <link rel="stylesheet" href="/static/css/details.css">
</head>

<body>
	<header>
		<a class="title" href="#"><img src="/static/images/logo.png" alt="logo" style="width:60px;"> Local Search System</a>
	</header>

	<div id="main_div" class="container">

      {% for item in items %}
        <h1>{{item.title}}</h1>
        {% if item.image != "" %}
          <img class="center" alt="Image Not Available" src={{item.image}} >
        {% endif %}
      {% endfor %}

      {% for paragraph in paragraphs %}
        <p> {{paragraph}} </p>
      {% endfor %}
	</div>
    <br/><br/><br/><br/>
	<script src="/static/js/index.js"></script>

</body>
</html>

Backup/LocalSearchSystem/WikiNews/templates/indexing.html
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Indexing</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="CSS/common.css">
    <link rel="stylesheet" href="CSS/indexing.css">
</head>
   
<body>  
    
    <header>
        <a class="title" href="#"><img src="./images/logo.png" alt="logo" style="width:60px;"> Local Search System</a> 
    </header>
    
    <div class="sidebar">
      <a href="user-management.html"><i class="fa fa-users" title="User management"></i> User Management</a> 
      <a href="Item-Management.html" class="active"><i class="fa fa-list" title="Item management"></i> Item Management</a>
      <a href="web-scrapping.html"><i class="fa fa-globe" title="Web scrapping" ></i> Web Scraping</a>
      <a href="index.html"><i class="fa fa-sign-out" title="Sign out"></i> Sign Out</a> 
    </div>
    
    <div class="container">
    
    
    </div>
    
    
    <div class="index_content">
        <h3 class="indexing"><b>Select Feature</b></h3>
        <form class="indexform" onsubmit="return validateIndexingForm();">
          <input type="checkbox" id="itemname" name="itemname">
          <label for="itemname"> Item Name</label><br>
          <input type="checkbox" id="itemdescription" name="itemdescription">
          <label for="itemdescription"> Item Description</label><br>
          <input type="checkbox" id="itemurl" name="itemurl"> 
          <label for="itemurl"> Item Website</label><br><br>
          <input class="indexbutton" type="submit" value="Submit">
        </form>
    </div>
    
    
    <script src="Js/indexings.js"></script>

</body>
    
</html>

Backup/LocalSearchSystem/WikiNews/templates/item-management.html
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Item Management</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="http://cdn.datatables.net/1.10.2/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="Stylesheet" href=" " "text="" javascript""="" src=""https://code.jquery.com/jquery-1.12.3.js">
    <script type="text/javascript" src="https://code.jquery.com/jquery-1.12.3.js"></script>  
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script type="text/javascript" src="http://code.jquery.com/jquery-1.7.1.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
    <link rel="stylesheet" href="/static/css/common.css">
</head>
	
<body>
	
    <header>
        <a class="title" href="#"><img src="/static/images/logo.png" alt="logo" style="width:60px;"> Local Search System</a>
    </header>
    
    <div class="sidebar">
      <a href="{% url 'User:usermanagement' %}"><i class="fa fa-users navtext" title="User management"></i> User Management</a>
      <a href="{% url 'WikiNews:itemmanagement' %}"  class="active"><i class="fa fa-list navtext" title="Item management"></i> Item Management</a>
      <a href="{% url 'WikiNews:webscrapping' %}"><i class="fa fa-globe navtext" title="Web scrapping" ></i> Web Scraping</a>
      <a href="{% url 'User:logout' %}"><i class="fa fa-sign-out navtext" title="Sign out"></i> Sign Out</a>
    </div>
    
    <div class="container-lg tabledata">
        <div class="table-responsive">
            <div class="table-wrapper">
                <div class="table-title">
                    <div class="row">
                        <div class="col-sm-8"><h2>Item <b>Details</b></h2></div>
                        <div class="col-sm-4">
                            <button type="button" class="btn btn-info add-new">Index</button>
                        </div>
                    </div>
                </div>
                <table id="item_table" class="table table-responsive table-bordered">
                    <thead>
                        <tr>
                            <th>Item Id</th>
                            <th>Item Name</th>
                            <th>Latest Updated</th>
							<th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for item in itemList %}
                        <tr>
                            <td>{{item.id}}</td>
                            <td><a onclick="itemDetail({{item.id}});" />{{item.title}}</td>
                            <td>{{item.lastUpdated}}</td>
                            <td>
                                <a class="add" title="Add" data-toggle="tooltip"><i class="material-icons">&#xE03B;</i></a>
                                <a class="edit" title="Edit" data-toggle="tooltip"><i class="material-icons">&#xE254;</i></a>
                                <a class="delete" title="Delete" data-toggle="tooltip" onClick="delItem({{item.id}});"><i class="material-icons">&#xE872;</i></a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>     

    <script src="/static/js/item-management.js"></script>
</body>
</html>

Backup/LocalSearchSystem/WikiNews/templates/opinions.html
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=windows-1252">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Details</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="/static/css/home.css">
  </head>
  <body>
    <header> <a class="title" href="#"><img src="/static/images/logo.png" alt="logo"

          style="width:60px;"> Local Search System</a></header>
    <nav id="p-namespaces" class="vector-menu vector-menu-tabs vectorTabs" role="navigation"

      style="background-position: left bottom; float: left; height: 2.5em; padding-left: 1px; background-image: linear-gradient(rgba(167, 215, 249, 0) 0px, rgb(167, 215, 249) 100%); background-repeat: no-repeat; background-size: 1px 100%;">
      <div class="body vector-menu-content">
        <ul class="vector-menu-content-list" style="list-style: none none; margin: 0px; padding: 0px; float: left; height: 40px;">
          <li id="ca-nstab-main" style="margin: 0px; padding: 0px; line-height: 1.125em; background-image: linear-gradient(to top, rgb(119, 193, 246) 0px, rgb(232, 242, 248) 1px, rgb(255, 255, 255) 100%); background-position: left bottom; background-repeat: repeat-x; float: left; display: block; height: 40px; white-space: nowrap;"><a

              href="{% url 'WikiNews:itemdetails' %}"

              style="text-decoration: none; color: rgb(6, 69, 173); background: linear-gradient(rgba(167, 215, 249, 0) 0px, rgb(167, 215, 249) 100%) right bottom / 1px 100% no-repeat; box-sizing: border-box; display: block; float: left; height: 3.07692em; position: relative; padding-top: 1.25em; padding-left: 8px; padding-right: 8px; font-size: 0.8125em; cursor: pointer;">Article</a></li>
          <li id="ca-main-talk" style="margin: 0px; padding: 0px; line-height: 1.125em; background-image: linear-gradient(to top, rgb(119, 193, 246) 0px, rgb(232, 242, 248) 1px, rgb(255, 255, 255) 100%); background-position: left bottom; background-repeat: repeat-x; float: left; display: block; height: 40px; white-space: nowrap;"><a

              href="{% url 'WikiNews:collaboration' %}"

              style="text-decoration: none; color: rgb(6, 69, 173); background: linear-gradient(rgba(167, 215, 249, 0) 0px, rgb(167, 215, 249) 100%) right bottom / 1px 100% no-repeat; box-sizing: border-box; display: block; float: left; height: 3.07692em; position: relative; padding-top: 1.25em; padding-left: 8px; padding-right: 8px; font-size: 0.8125em; cursor: pointer;">Collaboration</a></li>
          <li id="ca-nstab-comments" class="selected" style="margin: 0px; padding: 0px; line-height: 1.125em; background: rgb(255, 255, 255); float: left; display: block; height: 40px; white-space: nowrap;"><a

              href="{% url 'WikiNews:opinions' %}"

              style="text-decoration: none; color: rgb(32, 33, 34); background: linear-gradient(rgba(167, 215, 249, 0) 0px, rgb(167, 215, 249) 100%) right bottom / 1px 100% no-repeat; box-sizing: border-box; display: block; float: left; height: 3.07692em; position: relative; padding-top: 1.25em; padding-left: 8px; padding-right: 8px; font-size: 0.8125em; cursor: pointer;">Opinions</a></li>
        </ul>
      </div>
    </nav>
    <br>
    <br>
    <p><br>
    </p>
    <h1 class="firstHeading" style="color: rgb(0, 0, 0); margin: 0px 0px 0.25em; padding: 0px; overflow: visible; border-bottom: 1px solid rgb(162, 169, 177); font-size: 1.8em; font-weight: normal; font-family: &quot;Linux Libertine&quot;, Georgia, Times, serif; line-height: 1em; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;"

      lang="en"><b>Comments:</b><i>Seoul city Mayor Park Won-soon found dead,
        South Korean police confirm</i></h1>
    <div id="bodyContent" class="mw-body-content" style="position: relative; z-index: 0; font-size: calc(0.875em); line-height: 1.5em; color: rgb(32, 33, 34); font-family: sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
      <div id="contentSub" style="font-size: 11.76px; line-height: 1.2em; margin: 0px 0px 1.4em 1em; color: rgb(84, 89, 93); width: auto;"></div>
      <div id="jump-to-nav"></div>
      <a class="mw-jump-link" href="https://en.wikinews.org/wiki/Comments:Seoul_city_Mayor_Park_Won-soon_found_dead,_South_Korean_police_confirm#mw-head"

        style="text-decoration: none; color: rgb(11, 0, 128); background: none; display: block; clip: rect(1px, 1px, 1px, 1px); width: 1px; height: 1px; margin: -1px; border: 0px; padding: 0px; overflow: hidden; position: absolute !important;">Jump
        to navigation</a><a class="mw-jump-link" href="https://en.wikinews.org/wiki/Comments:Seoul_city_Mayor_Park_Won-soon_found_dead,_South_Korean_police_confirm#searchInput"

        style="text-decoration: none; color: rgb(11, 0, 128); background: none; display: block; clip: rect(1px, 1px, 1px, 1px); width: 1px; height: 1px; margin: -1px; border: 0px; padding: 0px; overflow: hidden; position: absolute !important;">Jump
        to search</a>
      <div id="mw-content-text" dir="ltr" class="mw-content-ltr" style="direction: ltr;"

        lang="en">
        <div class="lqt-talkpage">
          <div class="mw-parser-output">
            <div class="toccolours" id="commentary-header-lqt" style="border: 1px solid rgb(170, 170, 170); background-color: rgb(249, 249, 249); padding: 5px; font-size: 13.3px; text-align: center;">
              <p style="margin: 0.5em 0px;"><span style="color: #110601;">This
                  page is for commentary on the news. If you wish to point out a
                  problem in the article (e.g. factual error, etc), please use<span>&nbsp;</span><a

                    href="https://en.wikinews.org/wiki/Talk:Seoul_city_Mayor_Park_Won-soon_found_dead,_South_Korean_police_confirm"

                    title="Talk:Seoul city Mayor Park Won-soon found dead, South Korean police confirm"

                    style="text-decoration: none; background: rgba(0, 0, 0, 0) none repeat scroll 0% 0%;">its
                    regular collaboration page</a><span>&nbsp;</span>instead.
                  Comments on this page do not need to adhere to the<span>&nbsp;</span><a

                    href="https://en.wikinews.org/wiki/Wikinews:NPOV" class="mw-redirect"

                    title="Wikinews:NPOV" style="text-decoration: none; background: rgba(0, 0, 0, 0) none repeat scroll 0% 0%;">Neutral
                    Point of View</a><span>&nbsp;</span>policy. Please remain on
                  topic and avoid offensive or inflammatory comments where
                  possible. Try thought-provoking, insightful, or controversial.
                  Civil discussion and polite sparring make our comments pages a
                  fun and friendly place. Please think of this when posting.</span></p>
            </div>
          </div>
        </div>
      </div>
    </div>
    <p></p>
  </body>
</html>

Backup/LocalSearchSystem/WikiNews/templates/search-result.html
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Search Result</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="http://code.jquery.com/jquery-latest.js"></script>
    <script src="jquery.easyPaginate.js"></script>
    <link rel="stylesheet" href="CSS/index.css">
    <link rel="stylesheet" href="/static/css/search-result.css">
</head>

<body>  
    
    <header>
        <a class="title" href="#"><img src="/static/images/logo.png" alt="logo" style="width:60px;"> Local Search System</a>
        <a class="signout" href="{% url 'User:logout' %}"><i class="fa fa-sign-out" title="Sign out"></i> Sign Out</a>
    </header>

    <main>
        <p id="write"></p>
        <section class="searchResults"></section>
    </main>
    
    <div id="easyPaginate" class="pagination">
      <a href="#">&laquo;</a>
      <a class="active" href="#">1</a>
      <a href="#">2</a>
      <a href="#">3</a>
      <a href="#">4</a>
      <a href="#">5</a>
      <a href="#">6</a>
      <a href="#">&raquo;</a>
    </div>
    
    <script src="/static/js/search-result.js"></script>
</body>
</html>

Backup/LocalSearchSystem/WikiNews/templates/search.html
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Search Page</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="CSS/common.css">
    <link rel="stylesheet" href="/static/css/search.css">
  </head>
  <body>
    <header> <a class="title" href="#"><img src="/static/images/logo.png"

          alt="logo" style="width:60px;"> Local Search System</a> <a class="signout"

        href="{% url 'User:logout' %}"><i class="fa fa-sign-out navtext" title="Sign out"></i>
        Sign Out</a> </header>
    <div class="container">
      <form id="search_form" action="{% url 'WikiNews:searchresult' %}" class="overlay-content">
        <h2 class="heading">WikiNews Search</b></h2>
        <input placeholder="Enter Keyword" id="search_result" class="overlay-text"

          type="text"> <input class="overlay-button" value="Submit" type="submit">
      </form>
    </div>
<!--    <script src="/static/js/search.js"></script>-->
  </body>
</html>

Backup/LocalSearchSystem/WikiNews/templates/web-scrapping.html
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Web Scrapping</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="/static/css/common.css">
    <link rel="stylesheet" href="/static/css/webscrapping.css">
</head>
	
<body>
	
    <header>
        <a class="title" href="#"><img src="/static/images/logo.png" alt="logo" style="width:60px;"> Local Search System</a>
    </header>
    
    <div class="sidebar">
      <a href="{% url 'User:usermanagement' %}" ><i class="fa fa-users" title="User management"></i> User Management</a>
      <a href="{% url 'WikiNews:itemmanagement' %}"><i class="fa fa-list" title="Item management"></i> Item Management</a>
      <a href="{% url 'WikiNews:webscrapping' %}" class="active"><i class="fa fa-globe" title="Web scrapping" ></i> Web scrapping</a>
      <a href="{% url 'User:logout' %}"><i class="fa fa-sign-out" title="Sign out"></i> Sign out</a>
    </div>
 
    
    <div class="col-md-9 scrapform">
        <h2 class="heading">Web <b>scrapping</b></h2>
        <form onsubmit="return validateWebScrappingForm();" action="{% url 'WikiNews:scrapping' %}" method="POST">
            {% csrf_token %}
            <p class="weblink">Enter Website URL: </p>
            <input class="input" type="text" id="urlinput", name="urlinput">
            <input class="scrap" type="submit" value="scrap">
<!--            <button  type="submit" class="scrap" onclick="validateWebScrappingForm();">Scrap</button>-->
        </form>
    </div> 
    
    <script src="/static/js/web-scrapping.js"></script>
    
</body>
</html>