DjangoProject/LocalSearchSystem/User/urls.py
from django.urls import path, include
from .import views


app_name = 'User'

urlpatterns = [
    path('login', views.LoginView, name='loginview'),
    path('login', views.LogoutView, name = "logout"),
    path('usermanagement', views.UserManagementView, name = "usermanagement"),
    path('newuser', views.NewUserView),
    path('search/', include('haystack.urls')),
    path('del/<int:userId>',views.DelUser),
    path('ediuser',views.EditUser, name='edituser'),
]

DjangoProject/LocalSearchSystem/User/models.py
from django.db import models
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)

# Create your models here.

class WikiNewsUser(models.Model):
    id = models.AutoField(primary_key=True)
    username = models.CharField(max_length=200, null=True, unique=True)
    password = models.CharField(max_length=100)
    is_admin = models.BooleanField(default=True, blank=True)

    class Meta:
        db_table = 'WikiNewsUser'

DjangoProject/LocalSearchSystem/User/forms.py
from django.forms import ModelForm
from django import  forms
from .models import  WikiNewsUser


class NewUserForm(forms.Form):
    username = forms.CharField(label='User Name' ,max_length=255)
    password = forms.CharField(widget=forms.PasswordInput(), max_length=100, label='Password')
    password2 = forms.CharField(widget=forms.PasswordInput(), max_length=100, label='Confirm Password')
    isadmin = forms.BooleanField(label='Admin' ,initial=True, required=False)

    def clean(self):
        super(NewUserForm, self).clean()
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        password2 = self.cleaned_data['password2']
        user = WikiNewsUser.objects.filter(username=username)
        print(len(user))
        print(user)
        if len(user) > 0:
            self._errors['username'] = self.error_class(['This User name is already taken'])
        elif password and len(password) < 8:
                self._errors['password'] = self.error_class(['Password should contain atleast 8 characters'])
        elif password and password2 and password != password2:
                self._errors['password2'] = self.error_class(['Password and Confirm Password do not match'])
        else:
            return self.cleaned_data


class EditUserForm(forms.Form):
    edituserid = forms.IntegerField(label='edituserid')
    editusername = forms.CharField(label='editusername' ,max_length=255)
    editpassword = forms.CharField(widget=forms.PasswordInput(), max_length=100)
    editisadmin = forms.BooleanField(label='editisadmin')


class UserLoginForm(forms.Form):
    username = forms.CharField(label='User Name',max_length=100, required=True)
    password = forms.CharField(label='Password', widget=forms.PasswordInput(), max_length=100,required=True)

    def clean(self):
        super(UserLoginForm, self).clean()
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        user = WikiNewsUser.objects.filter(username=username, password=password)
        database_password =""
        for item in user:
            database_password = item.password
        # print(user.password)
        if len(user) == 0:
            self._errors['username'] = self.error_class(['Invalid username'])
            self._errors['password'] = self.error_class(['Invalid password'])
        elif password != database_password:
            self._errors['password'] = self.error_class(['Invalid password'])
        else:
            return self.cleaned_data

DjangoProject/LocalSearchSystem/User/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from .models import WikiNewsUser
from .import views
from .forms import NewUserForm, EditUserForm, UserLoginForm
from django.contrib.auth import authenticate, login, logout
from django.template.context_processors import csrf
from django.utils.datastructures import MultiValueDictKeyError
from django.core.paginator import  Paginator, InvalidPage, EmptyPage, PageNotAnInteger


# View function for Login operation
def LoginView(request):
    if request.method=='POST':
        userdetails = UserLoginForm(request.POST)
        if userdetails.is_valid():
            username = userdetails.cleaned_data['username']
            user = WikiNewsUser.objects.filter(username=username)
            request.session['username'] = user[0].username
            admin = False
            for field in user:
                admin = field.is_admin
            if admin:
                return UserManagementView(request)
            else:
                return HttpResponseRedirect('/wikinews/userhome/')

        else:
            return render(request, "index.html", {'form': userdetails})
    else:
        form = UserLoginForm(None)
        return render(request, 'index.html', {'form': form})


# View function for User List page
def UserManagementView(request):
    userList = WikiNewsUser.objects.all()
    return render(request, 'user-management.html', {'data': userList})


# View function for New User form
def NewUserView(request):
    if request.method == 'POST':
        newuserdetails = NewUserForm(request.POST)
        if newuserdetails.is_valid():
            model = WikiNewsUser()
            model.username = newuserdetails.cleaned_data['username']
            model.password = newuserdetails.cleaned_data['password']
            model.is_admin = newuserdetails.cleaned_data['isadmin']
            print(newuserdetails.cleaned_data['isadmin'])
            model.save()
            return HttpResponseRedirect('/user/usermanagement')
        else:
            return render(request, 'newuser.html', {'form': newuserdetails})
    else:
        form = NewUserForm(None)
        return render(request, 'newuser.html', {'form': form})


# View function for Logout operation
def LogoutView(request):
    del request.session['username']
    return HttpResponseRedirect('/user/login')



# View function for Delete User operation
def DelUser(request,userId):
    user=WikiNewsUser.objects.get(id=userId)
    user.delete()
    return  HttpResponseRedirect('/user/usermanagement')



# View function for Edit User operation
def EditUser(request):
    form = EditUserForm(request.POST)
    if request.method=='POST':
        try:
            userId = form.data['edituserid']
            user = WikiNewsUser.objects.get(id=userId)
            user.username = form.data['editusername']
            user.password = form.data['editpassword']
            try:
                is_admin = request.POST['editisadmin']
            except MultiValueDictKeyError:
                is_admin = False
            if 'editisadmin' in form.data:
                user.is_admin = True
            else:
                user.is_admin = False

            user.save()
        except:
            return HttpResponseRedirect('/user/usermanagement')
    return HttpResponseRedirect('/user/usermanagement')

DjangoProject/LocalSearchSystem/User/templates/index.html
{% load bootstrap3 %}
{% bootstrap_messages %}
<!DOCTYPE html>
<html lang="en">
<head >
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Login Page</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="/static/css/index.css">
</head>

<body>
    <header>
        <a class="title" href="#"><img src="/static/images/logo.png" alt="logo" style="width:60px;"> Local Search System</a>
    </header>

    <div class="container">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <img class="login_icon" src="/static/images/loginnew.png" alt="logo">
                <form action="{% url 'User:loginview' %}" method="post"><input type='hidden'/>
                    {%csrf_token %}
                    {% bootstrap_form form %}
                    <div class="form-group">
                        <input type="submit" class="button" value="Login"/><br>
                    </div>
                 </form>
            </div>
        </div>
    </div>

</body>
</html>

DjangoProject/LocalSearchSystem/User/templates/newuser.html
{% load bootstrap3 %} {% bootstrap_messages %}
<!DOCTYPE html>
<html lang="en">

<head>
	<title>Basic Form</title>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="http://cdn.datatables.net/1.10.2/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css">

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<link rel="stylesheet" href="/static/css/common.css">
    <link rel="stylesheet" href="/static/css/index.css">
	<style>
	.sidebar {
		margin-top: 90px;
	}
	.login_icon {
		margin-top: 120px;
	}
	</style>

</head>

<body>

     <header>
        <a class="title" href="#"><img src="/static/images/logo.png" alt="logo" style="width:60px;"> Local Search System</a>
    </header>

	 <div class="sidebar"> <a href="{% url 'User:usermanagement' %}" ><i class="fa fa-users navtext" title="User management"></i> User Management</a> <a href="{% url 'WikiNews:itemmanagement' %}"><i class="fa fa-list navtext" title="Item management"></i> Item Management</a> <a href="{% url 'WikiNews:webscrapping' %}"><i class="fa fa-globe navtext" title="Web scrapping" ></i> Web Scraping</a> <a href="{% url 'User:logout' %}"><i class="fa fa-sign-out navtext" title="Sign out"></i> Sign Out</a> </div>

	<div class="container">
		<div class="row">
			<div class="col-md-4 col-md-offset-4">
				<img class="login_icon" src="/static/images/newuser.png" alt="logo">
				<form action="/user/newuser" method="post">
					<input type='hidden' /> {%csrf_token %} {% bootstrap_form form %}
					<div class="form-group">
						<button class="button"> Submit </button>
					</div>
				</form>
			</div>
		</div>
	</div>
</body>

</html>

DjangoProject/LocalSearchSystem/User/templates/user-management.html
<!doctype html>
<html>

<head>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>User Management</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="http://cdn.datatables.net/1.10.2/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="Stylesheet" href=" " "text="" javascript""="" src=""https://code.jquery.com/jquery-1.12.3.js">
    <script type="text/javascript" src="https://code.jquery.com/jquery-1.12.3.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script type="text/javascript" src="http://code.jquery.com/jquery-1.7.1.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
	<link rel="stylesheet" href="/static/css/common.css">

</head>

<body>
	<header>
		<a class="title" href="#"><img src="/static/images/logo.png" alt="logo" style="width:60px;"> Local Search System</a>
	</header>

	<div class="sidebar"> <a href="{% url 'User:usermanagement' %}" class="active"><i class="fa fa-users navtext" title="User management"></i> User Management</a> <a href="{% url 'WikiNews:itemmanagement' %}"><i class="fa fa-list navtext" title="Item management"></i> Item Management</a> <a href="{% url 'WikiNews:webscrapping' %}"><i class="fa fa-globe navtext" title="Web scrapping" ></i> Web Scraping</a> <a href="{% url 'User:logout' %}"><i class="fa fa-sign-out navtext" title="Sign out"></i> Sign Out</a> </div>

	<div class="container-lg tabledata">
		<div class="table-responsive">
			<div class="table-wrapper">
				<div class="table-title">
					<div class="row">
						<div class="col-sm-8">
							<h2>User <b>Details</b></h2></div>
						<div class="col-sm-4">
							<a href="newuser.html" class="btn btn-info add-new" data-toggle="modal" data-target="#newuserModal" onclick="newUser();">Add New</a>
						</div>
					</div>
				</div>
				<table id="user_table" class="table table-responsive table-bordered">
					<thead>
						<tr>
							<th>User Id</th>
							<th>UserName</th>
							<th>Password</th>
							<th>Is Admin</th>
							<th>Actions</th>
						</tr>
					</thead>
					<tbody> {% for x in data %}
						<tr>
							<td>{{x.id}}</td>
							<td>{{x.username}}</td>
							<td style="-webkit-text-security: disc;">{{x.password}}</td>
							<td>{{x.is_admin}}</td>
							<td> <a class="add" title="Add" data-toggle="tooltip"><i class="material-icons">&#xE03B;</i></a> <a class="edit" title="Edit" data-toggle="modal" data-target="#edituserModal"><i class="material-icons">&#xE254;</i></a> <a class="delete" title="Delete" data-toggle="tooltip" onClick="delUser({{x.id}});"><i class="material-icons">&#xE872;</i></a> </td>
						</tr> {% endfor %} </tbody>
				</table>
			</div>
		</div>
	</div>
	<div class="modal" id="edituserModal" role="dialog">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal">&times;</button>
					<h4 class="modal-title">Edit User</h4>
				</div>
				<div class="modal-body">
					<form action="{% url 'User:edituser' %}" method="POST">
						{% csrf_token %}
					  <div class="form-group">
						<label for="edituserid">User Id</label>
						<input type="number" class="form-control" id="edituserid" name="edituserid" aria-describedby="emailHelp" readonly>
						<!--<small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small> -->
					  </div>
						<div class="form-group">
						<label for="editusername">User Name</label>
						<input type="text" class="form-control" id="editusername" name="editusername" placeholder="" readonly>
					  </div>
					  <div class="form-group">
						<label for="editpassword">Password</label>
						<input type="password" class="form-control" id="editpassword" name="editpassword" placeholder="">
					  </div>
					  <div class="form-check">
						<input type="checkbox" class="form-check-input" id="editisadmin" name="editisadmin">
						<label class="form-check-label" for="editisadmin">Admin</label>
					  </div>
						<div class="text-right">
					  		<button type="submit" class="btn btn-primary btn-lg">Update</button>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>

	<script src="/static/js/user-management.js"></script>
</body>
</html>